### ISSUE TITLE
unsafe CFile::from_raw

### ISSUE THREAD

**Issue by pacman82** [flier/rust-cfile#1]
Shouldn't `CFile::from_raw` be declared unsafe on account that the otherwise safe interface requires the file ptr to be valid? While the constructor checks for the argument to be unequal to `NULL` it can still point to an invalid `FILE *`.

**Comment by flier** [comment]
Agree, `CFile::from_raw` should be unsafe because we hard to validate it.

**Comment by flier** [comment]
Should be fixed in [v0.4.0](https://crates.io/crates/cfile/0.4.0), thanks

**Comment by pacman82** [comment]
Thank you!
