### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by burtonageo** [flier/rust-cfile#2]
A lot of methods in this crate rely on the `std::os::unix::*` module, which makes it impossible to use this crate on Windows. Could these be factored out into a `cfile::unix` module so we can use this crate everywhere?

**Comment by flier** [comment]
I have submit a [commit](https://github.com/flier/rust-cfile/commit/25560886effd8de5464d304138ea1cfc47e2d92c) to port to windows, you may try and give your feedback.

Thanks

**Comment by burtonageo** [comment]
Works perfectly for my use case, thank you 😊

**Comment by flier** [comment]
Should be fixed in [v0.4.0](https://crates.io/crates/cfile/0.4.0), thanks
